### PR TITLE
added sfx eat audio and Allow user to tap anywhere on splash screen

### PR DESCRIPTION
**Pull request by ashishkrr**
added sfx eat audio which plays randomly among those, when we drop right answer stone #1021

Allow user to tap anywhere on splash screen to move onto the level selection screen and excluded the close button area for tapping #1027

### CODE REVIEW

**Comment by Rajesh1041** [comment]
I can see that two audios are added, modify the title to reflect the same.
and please try to create separate PR according to different task.

**Comment by ashishkrr** [comment]
> I can see that two audios are added, modify the title to reflect the same. and please try to create separate PR according to different task.


One is already added rajesh, so that is reason i just have added rest two which are not present before.

**Comment by Rajesh1041** [comment]
I know that one audio is already present, i can see that too but title seems confusing. Also create separate PR for separate tickets since these tasks are not even related.

**Comment by Rajesh1041** [comment]
@burrage Hey Ben this PR has two tasks in same PR, i feel its cleaner to have each task have their separate PRs. Should we follow that and create separate PR for this one or should i merge it.

**Comment by burrage** [comment]
@Rajesh1041 @ashishkrr In general, we should stick to the 1 task = 1 PR model because it just makes life easier on the reviewer, merger, production maintainer, rollbacker...

Are the only changes for #1027 in start-scene.js? Since it is 3 lines and these are both pretty minor changes, we can make a one-time exception but in the future, let's please try to stick to 1 task = 1 PR. Thanks!

**Comment by ashishkrr** [comment]
> @Rajesh1041 @ashishkrr In general, we should stick to the 1 task = 1 PR model because it just makes life easier on the reviewer, merger, production maintainer, rollbacker...
> 
> Are the only changes for #1027 in start-scene.js? Since it is 3 lines and these are both pretty minor changes, we can make a one-time exception (only if Rajesh feels it is appropriate) but in the future, let's please try to stick to 1 task = 1 PR as a best practice. Thanks!

@burrage Thanks for clarification, will follow the 1 task = 1 PR, @Rajesh1041 I am closing this PR as you asked me earlier to create separate PR for good practice.

**Pull request closed without merging**
